#!/bin/sh

BOLD_YELLOW='\033[1;33m'
RESET='\033[0m'

set -e

if [ "$1" = "configure" ]; then
     printf "${BOLD_YELLOW}Run the daemon by invoking 'otd-daemon', or by enabling opentabletdriver.service${RESET}"
fi
